defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build-php-7.1:
    <<: *defaults
    docker:
      - image: circleci/php:7.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "composer.json" }}
      - run: composer install -n --prefer-dist
      - save_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "composer.json" }}
          paths:
            - ./vendor

  test-mysql-php-7.1:
    <<: *defaults
    docker:
      - image: circleci/php:7.1-node-browsers
      - image: killbill/killbill:0.20.10
      - image: killbill/mariadb:0.20
        environment:
        - MYSQL_ROOT_PASSWORD=root
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ .Branch }}-{{ checksum "composer.json" }}
      - run:
          name: Setup DDL
          command: |
            set +e
            count=0
            until mysqladmin ping -h 127.0.0.1 -u root --password=root --silent; do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))
              printf '.'
              sleep 5
            done
            set -e
      - run:
          name: Setup Kill Bill
          command: |
            set +e
            count=0
            until $(curl --output /dev/null --silent --fail http://127.0.0.1:8080/1.0/healthcheck); do
              if [[ "$count" == "25" ]]; then
                exit 1
              fi
              (( count++ ))

              printf '.'
              sleep 5
            done
            set -e
            curl -v \
                 -X POST \
                 -u admin:password \
                 -H 'Content-Type: application/json' \
                 -H 'X-Killbill-CreatedBy: CircleCI' \
                 -d '{"apiKey": "bob", "apiSecret": "lazar"}' \
                 "http://127.0.0.1:8080/1.0/kb/tenants?useGlobalDefault=true"
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            composer phpcs && composer test
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
workflows:
  version: 2
  build-and-test:
    jobs:
      - build-php-7.1
      - test-mysql-php-7.1:
          requires:
            - build-php-7.1
